apiVersion: /v1
kind: Service
metadata:
  name: control-plane
  namespace: memphis
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
  selector:
    app: memphis-control-plane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memphis-control-plane
  namespace: memphis
  labels:
    app: memphis-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memphis-control-plane
  template:
    metadata:
      name: memphis-control-plane
      labels:
        app: memphis-control-plane
    spec:
      containers:
        - name: memphis-control-plane
          image: 221323242847.dkr.ecr.eu-central-1.amazonaws.com/memphis-control-plane-staging:latest
          ports:
            - containerPort: 5555
          env:
          - name: ROOT_PASSWORD
            value: "123456"
          - name: BROKER_JWT
            value: "test"
