apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: memphis-broker-check
  local:
    push: true
deploy:
  helm:
    releases:
    - name: my-release
      chartPath: memphis-k8s/memphis/